spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    initialization-mode: always   
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/personality
    username: dbuser
    password: sanksn
    data: classpath:data.sql 
  